package auth

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestGenerateRandomString(t *testing.T) {
	tests := []struct {
		name   string
		length int
	}{
		{"short string", 8},
		{"medium string", 12},
		{"long string", 32},
		{"single character", 1},
	}

	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := generateRandomString(tt.length)
			if len(result) != tt.length {
				t.Errorf("expected length %d, got %d", tt.length, len(result))
			}
			for _, ch := range result {
				if !strings.ContainsRune(charset, ch) {
					t.Errorf("invalid character %q in generated string", ch)
				}
			}
			if tt.length > 1 {
				seen := make(map[string]bool)
				for range 10 {
					s := generateRandomString(tt.length)
					if seen[s] {
						t.Errorf("generated duplicate string: %s", s)
					}
					seen[s] = true
				}
			}
		})
	}
}

func TestGenerateRandomString_Uniqueness(t *testing.T) {
	seen := make(map[string]bool)
	for i := range 100 {
		s := generateRandomString(16)
		if seen[s] {
			t.Errorf("duplicate string after %d iterations: %s", i+1, s)
		}
		seen[s] = true
	}
}

func TestSetup_Disabled(t *testing.T) {
	cfg := Setup(false, "", "")
	if cfg.Enabled {
		t.Error("expected Enabled=false")
	}
	if cfg.Username != "" || cfg.Password != "" {
		t.Error("expected empty credentials when auth is disabled")
	}
}

func TestSetup_AutoGenerated(t *testing.T) {
	cfg := Setup(true, "", "")
	if !cfg.Enabled {
		t.Error("expected Enabled=true")
	}
	if len(cfg.Username) != 8 {
		t.Errorf("expected auto-generated username length 8, got %d", len(cfg.Username))
	}
	if len(cfg.Password) != 12 {
		t.Errorf("expected auto-generated password length 12, got %d", len(cfg.Password))
	}
}

func TestSetup_CustomCredentials(t *testing.T) {
	cfg := Setup(true, "admin", "secret123")
	if cfg.Username != "admin" {
		t.Errorf("expected username 'admin', got %q", cfg.Username)
	}
	if cfg.Password != "secret123" {
		t.Errorf("expected password 'secret123', got %q", cfg.Password)
	}
}

func TestExampleURL_AuthDisabled(t *testing.T) {
	cfg := Setup(false, "", "")
	url := "http://localhost:8080/test"
	if got := cfg.ExampleURL(url); got != url {
		t.Errorf("expected %q, got %q", url, got)
	}
}

func TestExampleURL_AuthEnabled(t *testing.T) {
	cfg := Setup(true, "user123", "pass456")
	url := "http://localhost:8080/api"
	expected := "curl -u user123:pass456 http://localhost:8080/api"
	if got := cfg.ExampleURL(url); got != expected {
		t.Errorf("expected %q, got %q", expected, got)
	}
}

func TestPrintInfo_NoPanic(t *testing.T) {
	Setup(false, "", "").PrintInfo()
	Setup(true, "u", "p").PrintInfo()
}

func TestMiddleware_Disabled(t *testing.T) {
	cfg := Setup(false, "", "")
	called := false
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { called = true })

	req := httptest.NewRequest("GET", "/", nil)
	w := httptest.NewRecorder()
	cfg.Middleware(next)(w, req)

	if !called {
		t.Error("Expected next handler to be called when auth is disabled")
	}
}

func TestMiddleware_Enabled_NoCredentials(t *testing.T) {
	cfg := Setup(true, "admin", "secret")

	req := httptest.NewRequest("GET", "/", nil)
	w := httptest.NewRecorder()
	cfg.Middleware(func(w http.ResponseWriter, r *http.Request) {})(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("Expected 401, got %d", w.Code)
	}
	if w.Header().Get("WWW-Authenticate") == "" {
		t.Error("Expected WWW-Authenticate header")
	}
}

func TestMiddleware_Enabled_WrongCredentials(t *testing.T) {
	cfg := Setup(true, "admin", "secret")

	req := httptest.NewRequest("GET", "/", nil)
	req.SetBasicAuth("admin", "wrong")
	w := httptest.NewRecorder()
	cfg.Middleware(func(w http.ResponseWriter, r *http.Request) {})(w, req)

	if w.Code != http.StatusUnauthorized {
		t.Errorf("Expected 401, got %d", w.Code)
	}
}

func TestMiddleware_Enabled_CorrectCredentials(t *testing.T) {
	cfg := Setup(true, "admin", "secret")
	called := false
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { called = true })

	req := httptest.NewRequest("GET", "/", nil)
	req.SetBasicAuth("admin", "secret")
	w := httptest.NewRecorder()
	cfg.Middleware(next)(w, req)

	if !called {
		t.Error("Expected next handler to be called with correct credentials")
	}
	if w.Code != http.StatusOK {
		t.Errorf("Expected 200, got %d", w.Code)
	}
}
